[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["xhwhis <hi@whis.me>"]
description = "[WIP] DataClot"
homepage = "https://github/dataclot"
repository = "https://github.com/dataclot/dataclot"
license = "Unlicense"
publish = ["dataclot"]

[workspace]
members = ["src/bin", "src/query", "src/server"]
resolver = "2"

[workspace.dependencies]
# workspace dependencies
query = { path = "src/query", version = "*" }
server = { path = "src/server", version = "*" }

# crates.io dependencies
async-trait = "0.1.74"
datafusion = { version = "32.0", features = ["simd"] }
futures = "0.3.29"
tokio = { version = "1.34", features = ["full"] }
