[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[env]
DATACLOD_CORE_PORT = 9973
DATACLOD_PASSWORD = "dataclod"
DATACLOD_LOG_LEVEL = "DEBUG"
TOKIO_CONSOLE_BIND = "0.0.0.0:6669"
IMAGE_TAG = { script = ["git rev-parse --short HEAD"] }
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.default]
alias = "build"

[tasks.build]
command = "cargo"
args = ["build", "--workspace", "--all-features"]

[tasks.build-all]
command = "cargo"
args = ["build", "--workspace", "--all-features", "--all-targets"]

[tasks.build-release]
command = "cargo"
args = ["build", "--workspace", "--all-features", "--release"]

[tasks.precommit]
dependencies = ["typos", "fmt-all", "fix", "clippy-fix"]

[tasks.predeploy]
dependencies = ["fmt-check", "check-all", "clippy-all", "test"]

[tasks.precheck]
dependencies = ["fmt-check", "check-all"]

[tasks.publish]
command = "cargo"
args = [
  "release",
  "publish",
  "--workspace",
  "--execute",
  "--no-confirm",
  "--registry",
  "crates-io",
]

[tasks.core]
command = "cargo"
args = ["run", "--bin", "dataclod-core"]

[tasks.core-release]
command = "cargo"
args = ["run", "--bin", "dataclod-core", "--release"]

[tasks.core-console]
env = { RUSTFLAGS = "--cfg tokio_unstable" }
command = "cargo"
args = ["run", "--bin", "dataclod-core", "--features", "console"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--check", "--all"]

[tasks.fmt-toml]
install_crate = { crate_name = "taplo", binary = "taplo", test_arg = "--version" }
command = "taplo"
args = ["fmt"]

[tasks.fmt-all]
dependencies = ["fmt", "fmt-toml"]

[tasks.check]
command = "cargo"
args = ["check", "--workspace", "--all-features"]

[tasks.check-all]
command = "cargo"
args = ["check", "--workspace", "--all-features", "--all-targets"]

[tasks.fix]
command = "cargo"
args = [
  "fix",
  "--workspace",
  "--all-features",
  "--all-targets",
  "--allow-staged",
]

[tasks.clippy]
env = { RUSTFLAGS = "-Dclippy::all" }
command = "cargo"
args = ["clippy", "--workspace", "--all-features"]

[tasks.clippy-all]
env = { RUSTFLAGS = "-Dclippy::all" }
command = "cargo"
args = ["clippy", "--workspace", "--all-features", "--all-targets"]

[tasks.clippy-fix]
command = "cargo"
args = [
  "clippy",
  "--workspace",
  "--all-features",
  "--all-targets",
  "--fix",
  "--allow-staged",
]

[tasks.test]
command = "cargo"
args = ["nextest", "run", "--workspace", "--all-features", "--all-targets"]

[tasks.typos]
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = "--version" }
command = "typos"
args = ["-w"]

[tasks.outdated]
command = "cargo"
args = ["outdated", "--workspace"]

[tasks.flamegraph-core]
install_crate = { crate_name = "flamegraph", binary = "cargo", test_arg = [
  "flamegraph",
  "--version",
] }
env = { CARGO_PROFILE_RELEASE_DEBUG = true }
command = "cargo"
args = ["flamegraph", "--bin", "dataclod-core"]

[tasks.core-image]
script = "docker build -t dataclod-core:$IMAGE_TAG -f $CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY/docker/core.Dockerfile $CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY"

[tasks.run-core-image]
script = "docker run -d -e DATACLOD_CORE_PORT=$DATACLOD_CORE_PORT -e DATACLOD_PASSWORD=$DATACLOD_PASSWORD -e TOKIO_CONSOLE_BIND=$TOKIO_CONSOLE_BIND -p 9973:9973 -p 6669:6669 --name dataclod-core dataclod-core:$IMAGE_TAG"
