mod st_asmvtgeom;
mod st_transform;
mod udfs;

use datafusion::prelude::SessionContext;

pub fn register_spatial_udfs(ctx: &SessionContext) {
    ctx.register_udf(udfs::STAreaUDF::udf());
    ctx.register_udf(udfs::STLengthUDF::udf());
    ctx.register_udf(udfs::STXUDF::udf());
    ctx.register_udf(udfs::STYUDF::udf());
    ctx.register_udf(udfs::STXMinUDF::udf());
    ctx.register_udf(udfs::STXMaxUDF::udf());
    ctx.register_udf(udfs::STYMinUDF::udf());
    ctx.register_udf(udfs::STYMaxUDF::udf());
    ctx.register_udf(udfs::STIsEmptyUDF::udf());
    ctx.register_udf(udfs::STIsValidUDF::udf());
    ctx.register_udf(udfs::STNPointsUDF::udf());
    ctx.register_udf(udfs::STSRIDUDF::udf());
    ctx.register_udf(udfs::STNumPointsUDF::udf());
    ctx.register_udf(udfs::STAsTextUDF::udf());
    ctx.register_udf(udfs::STAsEWKTUDF::udf());
    ctx.register_udf(udfs::STAsGeoJSONUDF::udf());
    ctx.register_udf(udfs::STGeometryTypeUDF::udf());
    ctx.register_udf(udfs::STCentroidUDF::udf());
    ctx.register_udf(udfs::STConvexHullUDF::udf());
    ctx.register_udf(udfs::STEnvelopeUDF::udf());
    ctx.register_udf(udfs::STBoundaryUDF::udf());
    ctx.register_udf(udfs::STMakeValidUDF::udf());
    ctx.register_udf(udfs::STBuildAreaUDF::udf());
    ctx.register_udf(udfs::STContainsUDF::udf());
    ctx.register_udf(udfs::STIntersectsUDF::udf());
    ctx.register_udf(udfs::STWithinUDF::udf());
    ctx.register_udf(udfs::STEqualsUDF::udf());
    ctx.register_udf(udfs::STCoversUDF::udf());
    ctx.register_udf(udfs::STCoveredByUDF::udf());
    ctx.register_udf(udfs::STTouchesUDF::udf());
    ctx.register_udf(udfs::STOverlapsUDF::udf());
    ctx.register_udf(udfs::BBoxIntersectsUDF::udf());
    ctx.register_udf(udfs::STDistanceUDF::udf());
    ctx.register_udf(udfs::STIntersectionUDF::udf());
    ctx.register_udf(udfs::STDifferenceUDF::udf());
    ctx.register_udf(udfs::STUnionUDF::udf());
    ctx.register_udf(udfs::STSplitUDF::udf());
    ctx.register_udf(udfs::Box2DUDF::udf());
    ctx.register_udf(udfs::STBufferUDF::udf());
    ctx.register_udf(udfs::STSimplifyUDF::udf());
    ctx.register_udf(udfs::STSimplifyPreserveTopologyUDF::udf());
    ctx.register_udf(udfs::STSimplifyVWUDF::udf());
    ctx.register_udf(udfs::STSetSRIDUDF::udf());
    ctx.register_udf(udfs::STDWithinUDF::udf());
    ctx.register_udf(udfs::STTranslateUDF::udf());
    ctx.register_udf(udfs::STConcaveHullUDF::udf());
    ctx.register_udf(udfs::STMakePointUDF::udf());
    ctx.register_udf(udfs::STMakeEnvelopeUDF::udf());
    ctx.register_udf(udfs::STTileEnvelopeUDF::udf());
    ctx.register_udf(udfs::STGeomFromTextUDF::udf());
    ctx.register_udf(udfs::STGeomFromEWKTUDF::udf());
    ctx.register_udf(udfs::STGeomFromWKBUDF::udf());
    ctx.register_udf(udfs::STGeomFromEWKBUDF::udf());
    ctx.register_udf(udfs::STGeomFromGeoJSONUDF::udf());

    ctx.register_udf(st_asmvtgeom::st_asmvtgeom());
    ctx.register_udf(st_transform::st_transform());
}
