name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - uses: taiki-e/install-action@taplo

      - name: install dependencies
        run: |
          rustc --version
          cargo --version
          sudo apt update
          sudo apt install -y libgeos-dev

      - name: spell check
        uses: crate-ci/typos@v1

      - name: taplo fmt
        run: taplo fmt --check --diff

      - name: cargo fmt
        run: cargo fmt --check --all

      - name: clippy lint
        run: cargo clippy --workspace --all-targets --all-features -- -D clippy::all

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: taiki-e/install-action@nextest

      - name: install dependencies
        run: |
          rustc --version
          cargo --version
          sudo apt update
          sudo apt install -y libgeos-dev

      - name: cargo build
        run: cargo build --workspace --all-targets --all-features

      # - name: cargo nextest
        # run: cargo nextest run --workspace --all-targets --all-features
